### ISSUE TITLE
Put on store.kde.org?

### ISSUE THREAD

**Issue by silverhook** [Takios/dolphin-deja-dup#1]
It’d be cool if your extension was available via https://store.kde.org/ – could you add it there?

**Comment by Takios** [comment]
Thanks for the suggestion.
I uploaded the files and they are now available at https://store.kde.org/p/1173176/

**Comment by silverhook** [comment]
Cool, thanks :+1:

**Comment by silverhook** [comment]
You might want to mention at least where to store them. For KDE4 at least, it doesn’t install from GHNS.
